version: "3"
services:
  node:
    build: .
    container_name: sakai-web-components
    # user: "node"
    # working_dir: /home/node/app
    # environment:
      # - NODE_ENV=production
      # - NPM_CONFIG_LOGLEVEL=info
    volumes:
      - ./:/home/node/app
    ports:
      - 6006:6006